//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Li_Luan_Van
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int ID { get; set; }
        public string MaTask { get; set; }
        public string NhanXet { get; set; }
        public int Diem { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
