//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Li_Luan_Van
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraoDoi
    {
        public int ID { get; set; }
        public string MSSV { get; set; }
        public string ChuDe { get; set; }
        public string ThongTin { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string MSGV { get; set; }
        public bool TTGV { get; set; }
        public bool TTSV { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
